include: package:lint/analysis_options_package.yaml
analyzer:
  strong-mode:
    # A value of false ensures that the type inference engine never implicitly casts
    # from dynamic to a more specific type.
    implicit-casts: false
    # A value of false ensures that the type inference engine never chooses the
    # dynamic type when it can’t determine a static type.
    implicit-dynamic: false
linter:
  rules:
    # Make constructors the first thing in every class
    sort_constructors_first: true
    # Good packages document everything
    public_member_api_docs: true
    # Always await.
    unawaited_futures: true
    always_declare_return_types: true
    cancel_subscriptions: true
    close_sinks: true
    only_throw_errors: true
    package_api_docs: true
