include: package:lint/package.yaml
linter:
  rules:
    # Make constructors the first thing in every class
    sort_constructors_first: true
    # Good packages document everything
    public_member_api_docs: true
    always_declare_return_types: true
    cancel_subscriptions: true
    close_sinks: true
    only_throw_errors: true
    package_api_docs: true
