name: json_cache
description: An object-oriented package for caching user data locally in json; a combinable layer on top of local storage packages that unifies them with an elegant caching API.
version: 1.1.2
homepage: https://dartoos.dev
repository: https://github.com/dartoos-dev/json_cache

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cross_local_storage: ^2.0.1
  encrypted_shared_preferences: ^3.0.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  localstorage: ^4.0.0+1
  mutex: ^3.0.0
  shared_preferences: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.2
