name: json_cache
description: An object-oriented package for caching user data locally in json; a combinable layer on top of local storage packages that unifies them as an elegant caching API.
version: 0.1.0
homepage: https://dartoos.dev
repository: https://github.com/dartoos-dev/json_cache

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mutex: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.6.0
