name: json_cache
description: An object-oriented package for caching user data locally in json; a combinable layer on top of local storage packages that unifies them.
version: 3.0.1
homepage: https://dartoos.dev
repository: https://github.com/dartoos-dev/json_cache

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  localstorage: ^4.0.1+4
  mutex: ^3.1.0
  safe_local_storage: ^1.0.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_test: ^1.0.1
  lint: ^2.0.1
  mocktail: ^1.0.0
  test: ^1.24.9
