name: json_cache
description: An object-oriented package for caching user data locally in json; a combinable layer on top of local storage packages that unifies them.
version: 1.5.2
homepage: https://dartoos.dev
repository: https://github.com/dartoos-dev/json_cache

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cross_local_storage: ^2.0.1
  flutter:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  hive: ^2.2.3
  localstorage: ^4.0.1+2
  mutex: ^3.0.1
  shared_preferences: ^2.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_test: ^1.0.1
  lint: ^2.0.1
  mocktail: ^0.3.0
  test: ^1.18.2
